# Generated by Django 5.1.6 on 2025-02-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todi',
            new_name='Todo',
        ),
    ]
